spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kissqa
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      default_schema: app
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    database: postgresql


facebook:
  client:
    clientId: 921039661285083
    clientSecret: 558d8992c48cea0cc48f884ee53aa156
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
rememberMe:
  privateKey: 123456498745631332

token:
  secret: 9SyECk96oDsTmXfogIieDI0cD/8Fp123jlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
  expirationTime: 18000000
